name: XConomy
main: net.th3shadowbroker.XConomy.main
author: Th3Shadowbroker
version: 1.0.0
website: http://crafter629.de

commands:
    xcon:
        description: All the admin stuff.
        permission: XConomy.admin
        usage: /xcon <info:set:add:del:create> [Player:Bank] [Amount]
        aliases: [xconomy, eco, money]
    balance:
        description: Check a players account-balance.
        permission: XConomy.player.balance
        usage: /balance [Player]
        aliases: [money]
